# Script generated by WinScript
# Unblock if downloaded (removes Mark of the Web / Zone.Identifier)
Unblock-File -Path $PSCommandPath -ErrorAction SilentlyContinue
# Check if the script is running as admin
$ProgressPreference = "SilentlyContinue"
$ErrorActionPreference = "SilentlyContinue"
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { Write-Host "This script requires administrator privileges."`n"Please run WinScript as an administrator." -ForegroundColor Red; pause ; exit }
Write-Host "-- Updating Winget" -ForegroundColor Green
$v = winget -v; if ([version]($v.TrimStart('v')) -lt [version]'1.7.0') { Write-Output '-- Old Winget version detected, upgrading.'; $prev = Get-Location; Set-Location $env:USERPROFILE; Invoke-WebRequest -Uri 'https://aka.ms/getwinget' -OutFile 'winget.msixbundle'; Add-AppPackage -ForceApplicationShutdown .\winget.msixbundle; Remove-Item .\winget.msixbundle; Set-Location $prev } else { Write-Output 'Winget is already up to date, skipping upgrade.' }
winget settings --enable BypassCertificatePinningForMicrosoftStore
$apps = @(
    "7zip.7zip",
    "Mozilla.Firefox",
    "qBittorrent.qBittorrent",
    "Microsoft.VCRedist.2015+.x64",
    "Microsoft.DotNet.DesktopRuntime.10"
    "AIMP.AIMP",
    "Gyan.FFmpeg",
    "DenoLand.Deno",
    "Discord.Discord",
    "CrystalDewWorld.CrystalDiskInfo",
    "Rizonesoft.Notepad3",
    "Python.Python.3.14",
    "AOMEI.Backupper",
    "Valve.Steam",
    "WiseCleaner.WiseProgramUninstaller",
    "ONLYOFFICE.DesktopEditors"
)

Write-Host "-- Installing these apps: "
Write-Host ("-- " + ($apps -join ", "))
foreach ($app in $apps) { winget install $app --accept-source-agreements --accept-package-agreements --force }
# Pause the script

Pause
# Exit the script
exit
